title: Jekyll Play
email: c2edevofficial@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The minimal Jekyll base template with I18n support to quickly start with.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
asset_base_url: /assets

google_analytics: # your google analytics id

future: true # Show blog post of future date
permalink: /blogs/:year/:month/:day/:title/

sass:
  style: compressed

# Build settings
markdown: kramdown

exclude:
  - .DS_Store
  - README.md
